version: 2

jobs:
  build:
    working_directory: ~/damn

    docker:
      - image: node:7

    steps:
      - checkout

      - restore_cache:
          keys:
            - damn-{{ .Branch }}-{{ checksum "package.json" }}
            - damn-{{ .Branch }}
            - damn-master-{{ checksum "package.json" }}
            - damn-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Run tests
          command: yarn test -- --coverage

      - run:
          name: Install coveralls
          command: yarn global add coveralls

      - run:
          name: Send coverage to coveralls.io
          command: cat coverage/lcov.info | coveralls

      - save_cache:
          key: damn-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.yarn
            - ~/damn/node_modules
